### ISSUE TITLE
Consider `disabled` property when firing events

### ISSUE THREAD

**Issue by michaelpg** [PolymerElements/iron-test-helpers#15]
Should mock interactions still fire when an element is disabled?

    myPaperButton.addEventListener('tap', fn);
    myPaperButton.disabled = true;
    MockInteractions.tap(myPaperButton);

I would expect this not to call fn(), but it does, because MockInteractions always fires the event.

**Comment by notwaldorf** [comment]
I think this has been fixed. `tap` now respects `pointer-events: none`: https://github.com/PolymerElements/iron-test-helpers/blob/master/mock-interactions.js#L101
