### ISSUE TITLE
MockInteractions.track() event.detail.state is always set to "end"

### ISSUE THREAD

**Issue by alexclemensua** [PolymerElements/iron-test-helpers#23]
track() function is useful when testing drag'n'drop events. An average onTrack (e.g. paper-tabs) function looks like this:
```
onTrack : function(event){
  switch(event.detail.state){
      case 'start':
          this.trackStart(event)
          break;
      case 'track' :
          this.track(event)
          break;
      case 'end' :
          this.trackEnd(event)
          break;
  }
    event.preventDefault()
}
```

but event.detail.state === "end" every time you run MockInteractions.track() because of this piece of code in polymer.html:

```
if (!hasLeftMouseButton(e)) {
  self.info.state = 'end';
  untrackDocument(self.info);
}
```

which makes testing anything drag'n'drop impossible with the current MockInteractions.track()

**Comment by bicknellr** [comment]
Have you updated to v1.0.4? This looks like it should have been fixed by https://github.com/PolymerElements/iron-test-helpers/commit/c28d14d5e49b99bec6f0e4aee23fb8fb8fa8377d.

**Comment by alexclemensua** [comment]
@bicknellr I can confirm that this is fixed.

**Comment by bicknellr** [comment]
Thanks for taking a look.
