### ISSUE TITLE
MockInteractions.tap should trigger only mouse events or touch events, not both

### ISSUE THREAD

**Issue by valdrinkoshi** [PolymerElements/iron-test-helpers#53]
Currently `MockInteractions.tap(node, { emulateTouch: true });` triggers `touchstart, touchend, mousedown, mouseup` in addition to `tap`. It should only trigger `touchstart, touchend`. Likewise for mouse events (`emulateTouch: false`), it should only trigger `mousedown, mouseup`.

**Comment by cdata** [comment]
I disagree. If all of the events would be triggered in practice, should we not emulate that behavior?

**Comment by valdrinkoshi** [comment]
If all these events were triggered in practice, it would mean that:
1. the device supports touch and mouse events
2. the user click and taps at the same time on the same node

Even if I believe is not a valid use-case, one could still simulate 2. by calling:
```javascript
MockInteractions.tap(node, { emulateTouch: false }); // simulate the mouse click
MockInteractions.tap(node, { emulateTouch: true }); // simulate the tap

**Comment by cdata** [comment]
On a phone, for example, all of the events will be fired when a user performs an action that would generate a `tap`.

**Comment by valdrinkoshi** [comment]
On a phone we'll have only `touch` events, not `mouse` events https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#Setting_up_the_event_handlers
On a chrome pixel, we can have both `touch` and `mouse` events, but not both of them during one user interaction. 

`touchstart` and `mousedown` will never happen synchronously, on the same user interaction, right?
